"""Format PR analysis results into a markdown comment for posting to Git platforms."""

from __future__ import annotations

_RISK_EMOJI = {
    "High": "\U0001f534",    # red circle
    "Medium": "\U0001f7e1",  # yellow circle
    "Low": "\U0001f7e2",     # green circle
}


def format_pr_comment(pr_record, base_url: str | None = None) -> str:
    """Build a markdown comment from a completed PrAnalysis record.

    Args:
        pr_record: A PrAnalysis ORM instance with completed analysis data.
        base_url: Optional CodeLens UI base URL for the "View full analysis" link.

    Returns:
        A markdown string ready to post as a PR comment.
    """
    risk = pr_record.risk_level or "Unknown"
    emoji = _RISK_EMOJI.get(risk, "\u2753")
    blast = pr_record.blast_radius_total or 0
    files = pr_record.files_changed or 0
    adds = pr_record.additions or 0
    dels = pr_record.deletions or 0

    impact = pr_record.impact_summary or {}
    drift = pr_record.drift_report or {}

    sections: list[str] = []

    # Header
    sections.append("## CodeLens Architecture Analysis\n")
    sections.append(
        f"**Risk Level:** {emoji} {risk} "
        f"| **Blast Radius:** {blast} nodes "
        f"| **Files Changed:** {files} (+{adds} / -{dels})\n"
    )

    # Impact summary
    downstream = impact.get("downstream_count", 0)
    upstream = impact.get("upstream_count", 0)
    by_type = impact.get("by_type", {})
    type_breakdown = (
        ", ".join(f"{v} {k}" for k, v in by_type.items()) if by_type else ""
    )
    changed = pr_record.changed_node_count or 0
    changed_line = f"**Changed nodes:** {changed}"
    if type_breakdown:
        changed_line += f" ({type_breakdown})"

    impact_lines = [
        "### Impact Summary\n",
        f"- {changed_line}",
        f"- **Downstream affected:** {downstream} nodes",
        f"- **Upstream dependents:** {upstream} nodes",
    ]

    transactions = impact.get("transactions_affected", [])
    if transactions:
        impact_lines.append(f"- **Transactions affected:** {', '.join(transactions)}")

    sections.append("\n".join(impact_lines) + "\n")

    # Cross-technology impact (conditional)
    cross_tech = impact.get("cross_tech", [])
    if cross_tech:
        ct_lines = ["### Cross-Technology Impact\n"]
        for ct in cross_tech:
            ct_lines.append(f"- {ct['kind']}: `{ct['name']}`")
        sections.append("\n".join(ct_lines) + "\n")

    # Architecture drift (conditional)
    if drift.get("has_drift"):
        drift_lines = ["### Architecture Drift\n"]
        for dep in drift.get("potential_new_module_deps", []):
            from_mod = dep["from_module"]
            to_mod = dep["to_module"]
            drift_lines.append(
                f"- New module dependency: `{from_mod}` \u2192 `{to_mod}`"
            )
        for cycle in drift.get("circular_deps_affected", []):
            drift_lines.append(
                f"- Circular dependency: {' \u2192 '.join(f'`{m}`' for m in cycle)}"
            )
        for f in drift.get("new_files_outside_modules", []):
            drift_lines.append(f"- New file outside modules: `{f}`")
        sections.append("\n".join(drift_lines) + "\n")

    # AI analysis (conditional)
    if pr_record.ai_summary:
        sections.append(f"### AI Analysis\n\n{pr_record.ai_summary}\n")

    # Footer
    footer = "\n---\n*Generated by CodeLens"
    if base_url:
        url = (
            f"{base_url.rstrip('/')}/projects/{pr_record.repository_id}"
            f"/pull-requests/{pr_record.id}"
        )
        footer += f" \u2022 [View full analysis]({url})"
    footer += "*"
    sections.append(footer)

    return "\n".join(sections)
